
export const GET_CURRENCIES = "GET_CURRENCIES";
export const GET_CURRENCIES_RATES = "GET_CURRENCIES_RATES";
export const GET_INPUT_AMOUNT = "GET_INPUT_AMOUNT";
export const GET_BASE_RATE = "GET_BASE_RATE";
export const GET_CHANGE_RATE = "GET_CHANGE_RATE";
export const GET_CURRENCY_TO = "GET_CURRENCY_TO";
export const GET_CURRENCY_FROM = "GET_CURRENCY_FROM";